from fpdf import FPDF
import datetime
import os
import pandas as pd
import hashlib

class ClinicalReportGenerator(FPDF):
    """
    Medical-Grade Clinical Decision Support (CDS) Report Generator.
    Aligned with ACC/AHA structural reporting standards.
    """
    def __init__(self, logo_path="app/assets/logo.png", audit_hash=None):
        super().__init__()
        self.logo_path = logo_path
        self.set_auto_page_break(auto=True, margin=15)
        self.report_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        self.report_id = hashlib.md5(self.report_date.encode()).hexdigest()[:8].upper()
        self.audit_hash = audit_hash or "N/A"

    def header(self):
        # Professional Clinical Header
        self.set_fill_color(24, 43, 73) # Deep Clinical Navy
        self.rect(0, 0, 210, 35, 'F')
        
        if os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 20)
        
        self.set_font('helvetica', 'B', 22)
        self.set_text_color(255, 255, 255)
        self.set_xy(35, 10)
        self.cell(0, 10, 'CardioSense AI', new_x="LMARGIN", new_y="NEXT")
        
        self.set_font('helvetica', 'B', 9)
        self.set_xy(35, 20)
        self.cell(0, 8, 'CLINICAL DECISION SUPPORT - RISK STRATIFICATION REPORT', new_x="LMARGIN", new_y="NEXT")
        
        # Meta Info
        self.set_font('helvetica', '', 9)
        self.set_xy(160, 8)
        self.cell(40, 5, f"REF ID: {self.report_id}", new_x="LMARGIN", new_y="NEXT", align='R')
        self.set_xy(160, 13)
        self.cell(40, 5, f"DATE: {self.report_date.split(' ')[0]}", new_x="LMARGIN", new_y="NEXT", align='R')
        self.set_xy(160, 18)
        self.cell(40, 5, f"AUDIT: {self.audit_hash[:8]}", new_x="LMARGIN", new_y="NEXT", align='R')
        
        self.set_text_color(0)
        self.set_xy(10, 40)

    def footer(self):
        self.set_y(-25)
        self.set_font('helvetica', 'I', 7)
        self.set_text_color(100)
        
        # Legal CDS Disclaimer
        confidential = "CONFIDENTIAL MEDICAL RECORD (Protected Health Information)"
        self.cell(0, 5, confidential, new_x="LMARGIN", new_y="NEXT", align='C')
        
        disclaimer = "DISCLAIMER: This report is generated by an automated CDS engine. It is intended to assist medical professionals and is NOT a standalone diagnosis. Final clinical assessment requires physician interpretation."
        self.multi_cell(0, 4, disclaimer, align='C')
        
        self.set_font('helvetica', '', 8)
        self.cell(0, 8, f'Page {self.page_no()} | Generated by CardioSense Distributed Intelligence v2.1', align='C')

    def section_title(self, title):
        self.ln(5)
        self.set_font('helvetica', 'B', 12)
        self.set_fill_color(240, 245, 250)
        self.set_text_color(24, 43, 73)
        self.cell(0, 10, f" {title.upper()}", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0)
        self.ln(3)

    def add_demographics(self):
        self.set_font('helvetica', 'B', 10)
        self.cell(0, 10, "PATIENT & CLINICAL CONTEXT", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        
        self.set_font('helvetica', 'B', 9)
        self.cell(45, 7, "Patient ID (Pseudonym):", 0)
        self.set_font('helvetica', '', 10)
        self.cell(50, 7, f"CSAI-{self.report_id}", 0)
        
        self.set_font('helvetica', 'B', 9)
        self.cell(45, 7, "Assessing Physician:", 0)
        self.set_font('helvetica', '', 10)
        self.cell(50, 7, "System Automated Audit", new_x="LMARGIN", new_y="NEXT")
        
        self.set_font('helvetica', 'B', 9)
        self.cell(45, 7, "Medical Facility:", 0)
        self.set_font('helvetica', '', 10)
        self.cell(50, 7, "Digital Diagnostic Center", 0)
        self.ln(10)

    def add_executive_summary(self, prediction, probability, reasoning, overrides, confidence=None):
        risk_pct = probability[0][1] * 100
        status = "CRITICAL (Crisis Alert)" if overrides else ("POSITIVE (High Risk)" if prediction[0] == 1 else "NEGATIVE (Low Risk)")
        color = (200, 0, 0) if (prediction[0] == 1 or overrides) else (40, 167, 69)
        
        self.set_draw_color(200, 200, 200)
        self.rect(self.get_x(), self.get_y(), 190, 50)
        
        self.set_font('helvetica', 'B', 14)
        self.set_xy(15, self.get_y()+5)
        self.set_text_color(*color)
        self.cell(100, 10, f"Status: {status}", new_x="LMARGIN", new_y="NEXT")
        
        self.set_text_color(0)
        self.set_font('helvetica', 'B', 10)
        self.set_x(15)
        self.cell(50, 8, "Risk Probability Score:", 0)
        self.set_font('helvetica', 'B', 14)
        self.cell(0, 8, f"{risk_pct:.1f}%", new_x="LMARGIN", new_y="NEXT")
        
        if confidence:
            self.set_font('helvetica', 'B', 9)
            self.set_x(15)
            self.cell(50, 8, "Model Confidence Score:", 0)
            conf_color = (0, 128, 0) if confidence['level'] == 'HIGH' else (252, 196, 25) if confidence['level'] == 'MODERATE' else (200, 0, 0)
            self.set_text_color(*conf_color)
            self.cell(0, 8, f"{confidence['level']} ({confidence['score']*100:.1f}%)", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(0)

        self.set_font('helvetica', 'B', 9)
        self.set_x(15)
        self.cell(0, 8, "Primary Clinical Logic Summary:", new_x="LMARGIN", new_y="NEXT")
        self.set_font('helvetica', 'I', 10)
        self.set_x(15)
        self.multi_cell(180, 6, reasoning)
        
        self.set_xy(10, 110)

    def add_clinical_assessment(self, input_df, assessment, overrides):
        self.section_title("1. Comprehensive Clinical Assessment")
        
        # Quick vitals check
        data = input_df.iloc[0].to_dict()
        self.set_font('helvetica', 'B', 9)
        self.cell(45, 7, f"AGE: {data['age']}", 0)
        self.cell(45, 7, f"BP: {data['trestbps']} mmHg", 0)
        self.cell(45, 7, f"CHOLEST: {data['chol']} mg/dL", 0)
        self.cell(45, 7, f"MAX HR: {data['thalach']}", new_x="LMARGIN", new_y="NEXT")
        
        self.ln(3)
        self.set_font('helvetica', 'B', 10)
        self.cell(0, 8, "Physiological Guideline Alignment (ACC/AHA)", new_x="LMARGIN", new_y="NEXT")
        
        # Table
        self.set_font('helvetica', 'B', 9)
        self.set_fill_color(240, 240, 240)
        self.cell(50, 8, "Clinical Metric", 1, 0, 'C', fill=True)
        self.cell(100, 8, "Guideline Stage / Analysis", 1, 0, 'C', fill=True)
        self.cell(40, 8, "Severity", 1, new_x="LMARGIN", new_y="NEXT", align='C', fill=True)
        
        self.set_font('helvetica', '', 9)
        for row in assessment:
            sev_color = (200, 0, 0) if row['severity'] in ['CRITICAL', 'HIGH'] else (252, 196, 25) if row['severity'] == 'MODERATE' else (0, 0, 0)
            self.cell(50, 8, row['factor'], 1)
            self.cell(100, 8, row['status'], 1)
            self.set_font('helvetica', 'B', 9)
            self.set_text_color(*sev_color)
            self.cell(40, 8, row['severity'], 1, new_x="LMARGIN", new_y="NEXT", align='C')
            self.set_text_color(0)
            self.set_font('helvetica', '', 9)

        if overrides:
            self.ln(2)
            self.set_text_color(200, 0, 0)
            self.set_font('helvetica', 'B', 10)
            self.cell(0, 8, "!!! ACTIVE CLINICAL CRITICAL OVERRIDES", new_x="LMARGIN", new_y="NEXT")
            self.set_font('helvetica', '', 9)
            for o in overrides:
                self.set_x(15) # Explicit indent
                # Use explicit width (185) instead of 0 to avoid space calculation errors
                self.multi_cell(185, 5, f"- {o['reason']}", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(0)

    def add_interpretability(self, shap_plot_path, radar_plot_path=None):
        self.section_title("2. Machine Learning Attribution Analysis")
        self.set_font('helvetica', '', 10)
        self.multi_cell(0, 6, "Internal model attribution scores using SHAP. This visualizes the clinical weight each factor contributed toward the final risk probability.")
        
        if shap_plot_path and os.path.exists(shap_plot_path):
            self.image(shap_plot_path, x=15, w=180)
            self.ln(5)
            
        if radar_plot_path and os.path.exists(radar_plot_path):
            self.set_font('helvetica', 'B', 10)
            self.cell(0, 10, "Clinical Profile Optimization (Current vs Target)", new_x="LMARGIN", new_y="NEXT")
            self.image(radar_plot_path, x=45, w=120)
            self.ln(5)

    def add_intervention_roadmap(self, opt_results, roadmap=None):
        self.section_title("3. Intervention & Recovery Roadmap")
        
        if opt_results:
            self.set_font('helvetica', 'B', 10)
            self.cell(0, 8, "Least Effort Path (AI-Optimized Strategy)", new_x="LMARGIN", new_y="NEXT")
            self.set_font('helvetica', '', 10)
            target_risk = opt_results.get('final_prob', 0) * 100
            self.multi_cell(0, 6, f"The engine has identified a high-efficiency path to reach a {target_risk:.1f}% risk profile. This strategy prioritizes interventions with the highest risk-reduction-to-effort ratio.")
            self.ln(2)
            
        if roadmap:
            # Table for Roadmap
            self.set_font('helvetica', 'B', 8)
            self.set_fill_color(240, 240, 240)
            self.cell(30, 8, "Factor", 1, 0, 'C', fill=True)
            self.cell(80, 8, "Clinical Action", 1, 0, 'C', fill=True)
            self.cell(50, 8, "Clinical Impact", 1, 0, 'C', fill=True)
            self.cell(30, 8, "Priority", 1, new_x="LMARGIN", new_y="NEXT", align='C', fill=True)
            
            self.set_font('helvetica', '', 8)
            for step in roadmap:
                p_color = (200, 0, 0) if step['priority'] == 'HIGH' else (0, 0, 0)
                self.cell(30, 8, step['factor'], 1)
                self.cell(80, 8, step['action'], 1)
                self.cell(50, 8, step['impact'], 1)
                self.set_font('helvetica', 'B', 8)
                self.set_text_color(*p_color)
                self.cell(30, 8, step['priority'], 1, new_x="LMARGIN", new_y="NEXT", align='C')
                self.set_text_color(0)
                self.set_font('helvetica', '', 8)
            self.ln(5)

    def add_recommendations(self, recs):
        self.section_title("4. Actionable Clinical Recommendations")
        for r in recs:
            p = r['priority'].upper()
            color = (210, 0, 0) if p == 'HIGH' else (0, 0, 0)
            self.set_font('helvetica', 'B', 10)
            self.set_text_color(*color)
            self.cell(0, 8, f"[{p} PRIORITY] {r['title']}", new_x="LMARGIN", new_y="NEXT")
            self.set_text_color(0)
            self.set_font('helvetica', '', 10)
            self.multi_cell(0, 6, f"Rationale: {r['rationale']}")
            self.ln(3)

    def add_signoff(self):
        self.ln(10)
        self.set_font('helvetica', 'B', 10)
        self.cell(0, 10, "CLINICAL SIGN-OFF", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)
        
        curr_y = self.get_y()
        self.line(10, curr_y, 80, curr_y)
        self.line(130, curr_y, 200, curr_y)
        self.ln(2)
        self.set_font('helvetica', '', 9)
        self.cell(70, 5, "Interpreting Physician Signature", 0, 0, 'C')
        self.cell(50)
        self.cell(70, 5, "Date / Timestamp", 0, 0, 'C')

    def generate_report(self, input_df, prediction, probability, shap_plot_path, recs, reasoning=None, overrides=None, assessment=None, opt_results=None, roadmap=None, observations=None, confidence=None, radar_plot_path=None):
        self.add_page()
        self.add_demographics()
        self.add_executive_summary(prediction, probability, reasoning, overrides, confidence)
        self.add_clinical_assessment(input_df, assessment, overrides)
        self.add_interpretability(shap_plot_path, radar_plot_path)
        self.add_intervention_roadmap(opt_results, roadmap)
        self.add_recommendations(recs)
        if observations:
            self.ln(5)
            self.section_title("Additional Clinician Notes")
            self.multi_cell(0, 7, observations)
        self.add_signoff()
        return self.output()
