from fpdf import FPDF
import datetime
import os
import pandas as pd

class ClinicalReportGenerator(FPDF):
    def __init__(self, logo_path="app/assets/logo.png"):
        super().__init__()
        self.logo_path = logo_path
        self.set_auto_page_break(auto=True, margin=15)
        self.report_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    def header(self):
        # Logo
        if os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 33)
        
        # Title
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(0, 51, 102) # Deep clinical blue
        self.cell(80)
        self.cell(100, 10, 'CardioSense AI', border=0, ln=0, align='R')
        self.ln(5)
        
        self.set_font('helvetica', 'I', 10)
        self.cell(80)
        self.cell(100, 10, 'Clinical Risk Assessment Report', border=0, ln=1, align='R')
        
        # Line break
        self.ln(10)
        self.set_draw_color(0, 51, 102)
        self.line(10, 45, 200, 45)
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        
        # Medical Disclaimer
        disclaimer = "DISCLAIMER: This report is generated by an AI system for clinical decision support and should be reviewed by a qualified medical professional. It does not constitute a final diagnosis."
        self.multi_cell(0, 5, disclaimer, align='C')
        
        # Page number
        self.cell(0, 10, f'Page {self.page_no()} | Generated on {self.report_date}', 0, 0, 'C')

    def section_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_fill_color(230, 240, 250)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, f" {title}", ln=True, fill=True)
        self.ln(4)

    def add_clinical_profile(self, input_df: pd.DataFrame):
        self.section_title("1. Patient Clinical Profile")
        self.set_font('helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        
        data = input_df.iloc[0].to_dict()
        col_width = 45
        
        # Create a grid-like display
        items = list(data.items())
        
        # Mappings for categorical display
        MAPPINGS = {
            'sex': {0: "Female", 1: "Male"},
            'cp': {1: "Typ Angina", 2: "Atyp Angina", 3: "Non-Anginal", 4: "Asymptom"},
            'fbs': {0: "No", 1: "Yes"},
            'restecg': {0: "Normal", 1: "ST Abnorm", 2: "Hypertrophy"},
            'exang': {0: "No", 1: "Yes"},
            'slope': {1: "Upsloping", 2: "Flat", 3: "Downsloping"},
            'thal': {3: "Normal", 6: "Fixed Defect", 7: "Revers Defect"}
        }

        for i in range(0, len(items), 3):
            row_items = items[i:i+3]
            for key, val in row_items:
                display_name = key.replace('_', ' ').upper()
                self.set_font('helvetica', 'B', 9)
                self.cell(col_width, 7, f"{display_name}:", border=0)
            self.ln()
            for key, val in row_items:
                display_val = MAPPINGS.get(key, {}).get(val, val)
                self.set_font('helvetica', '', 10)
                self.cell(col_width, 7, f"{display_val}", border=0)
            self.ln(2)
        self.ln(5)

    def add_risk_assessment(self, prediction, probability):
        self.section_title("2. Diagnostic Risk Assessment")
        
        risk_val = probability[0][1] * 100
        status = "POSITIVE (High Risk)" if prediction[0] == 1 else "NEGATIVE (Low Risk)"
        color = (200, 0, 0) if prediction[0] == 1 else (0, 128, 0)
        
        self.set_font('helvetica', 'B', 12)
        self.cell(60, 10, "Assessment Result:", 0)
        self.set_text_color(*color)
        self.cell(0, 10, status, 0, 1)
        
        self.set_text_color(0)
        self.set_font('helvetica', '', 11)
        self.cell(60, 10, "Calculated Probability:", 0)
        self.set_font('helvetica', 'B', 11)
        self.cell(0, 10, f"{risk_val:.2f}%", 0, 1)
        
        # Add a small description
        self.set_font('helvetica', 'I', 10)
        desc = "The probability represents the likelihood of significant coronary artery disease based on the ensemble model behavior."
        self.multi_cell(0, 7, desc)
        self.ln(5)

    def add_clinical_drivers(self, shap_plot_path):
        self.section_title("3. Clinical Driver Analysis (SHAP)")
        self.set_font('helvetica', '', 10)
        self.multi_cell(0, 6, "The following analysis illustrates how each clinical factor influenced the current risk score. Red bars indicate factors increasing risk, while blue bars indicate factors decreasing risk.")
        
        if os.path.exists(shap_plot_path):
            # Center the image
            self.image(shap_plot_path, x=15, w=180)
            self.ln(5)
        else:
            self.set_font('helvetica', 'I', 10)
            self.cell(0, 10, "Driver analysis visualization unavailable.", ln=True)

    def add_simulation_results(self, sim_results):
        if not sim_results:
            return
            
        self.section_title("4. Intervention Simulation (What-If Analysis)")
        self.set_font('helvetica', '', 10)
        self.multi_cell(0, 6, "This section projects the impact of specific clinical interventions on the patient's risk profile.")
        self.ln(2)
        
        # Simulation Table Header
        self.set_font('helvetica', 'B', 10)
        self.set_fill_color(240, 240, 240)
        self.cell(95, 8, "Vitals Modified", 1, 0, 'C', fill=True)
        self.cell(95, 8, "Projected Risk Outcome", 1, 1, 'C', fill=True)
        
        # Table Body
        self.set_font('helvetica', '', 10)
        
        # Consistent mapping for simulation updates
        UPDATE_MAPPINGS = {
            'slope': {1: "Upsloping", 2: "Flat", 3: "Downsloping"},
            'thal': {3: "Normal", 6: "Fixed Defect", 7: "Revers Defect"}
        }
        
        updates_list = []
        for k, v in sim_results['updates'].items():
            val_display = UPDATE_MAPPINGS.get(k, {}).get(v, v)
            updates_list.append(f"{k.upper()}: {val_display}")
            
        updates_str = ", ".join(updates_list)
        self.multi_cell(95, 10, updates_str, border=1, align='L')
        
        # Risk Delta
        curr_y = self.get_y()
        self.set_xy(105, curr_y - 10) # Adjust Y if multi_cell wrapped
        
        delta = sim_results['delta'] * 100
        new_prob = sim_results['new_prob'] * 100
        
        delta_color = (0, 128, 0) if delta < 0 else (200, 0, 0)
        self.set_text_color(*delta_color)
        result_text = f"{new_prob:.1f}% ({delta:+.1f}% change)"
        self.cell(95, 10, result_text, 1, 1, 'C')
        
        self.set_text_color(0)
        self.ln(5)

    def add_recommendations(self, recs):
        self.section_title("5. Targeted Intervention Plan")
        
        if not recs:
            self.set_font('helvetica', 'I', 10)
            self.cell(0, 10, "No high-priority clinical interventions identified at this stage.", ln=True)
            return

        for r in recs:
            # Priority Badge
            p = r['priority'].upper()
            color = (255, 75, 75) if p == 'HIGH' else (252, 196, 25) if p == 'MODERATE' else (51, 154, 240)
            
            self.set_font('helvetica', 'B', 10)
            self.set_text_color(*color)
            self.cell(35, 8, f"[{p} PRIORITY]", 0, 0)
            
            self.set_text_color(0)
            self.set_font('helvetica', 'B', 11)
            self.cell(0, 8, r['title'], ln=True)
            
            self.set_font('helvetica', '', 10)
            self.multi_cell(0, 6, f"Clinical Rationale: {r['rationale']}")
            self.ln(3)
            
    def add_observations(self, observations):
        if not observations or observations.strip() == "":
            return
            
        self.section_title("Clinician's Observations")
        self.set_font('helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 7, observations)
        self.ln(5)

    def add_safety_metrics(self, confidence, safety_warnings):
        self.section_title("Model Integrity & Safety Analysis")
        
        # Confidence Metric
        self.set_font('helvetica', 'B', 11)
        self.cell(50, 8, "Prediction Confidence:", 0)
        
        c_color = tuple(int(confidence['color'].lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
        self.set_text_color(*c_color)
        self.cell(0, 8, f"{confidence['level']} ({confidence['score']}%)", ln=True)
        
        self.set_text_color(100, 100, 100)
        self.set_font('helvetica', 'I', 9)
        self.multi_cell(0, 6, confidence['description'])
        self.ln(4)
        
        # OOD Warnings
        if safety_warnings:
            self.set_text_color(200, 0, 0)
            self.set_font('helvetica', 'B', 10)
            self.cell(0, 8, "SYSTEM INTEGRITY ALERTS:", ln=True)
            self.set_font('helvetica', '', 9)
            for w in safety_warnings:
                self.cell(5) # Indent
                self.multi_cell(0, 5, f"- {w}")
            self.ln(2)
            self.set_font('helvetica', 'I', 9)
            self.multi_cell(0, 5, "Note: These warnings indicate the patient profile deviates from the primary training population. Results should be interpreted with higher clinical scrutiny.")
        else:
            self.set_text_color(0, 128, 0)
            self.set_font('helvetica', 'I', 10)
            self.cell(0, 8, "Internal validation checks: PASSED (Data within training bounds)", ln=True)
            
        self.set_text_color(0)
        self.ln(5)

    def generate_report(self, input_df, prediction, probability, shap_plot_path, recs, sim_results=None, observations=None, confidence=None, safety_warnings=None):
        self.add_page()
        self.add_clinical_profile(input_df)
        self.add_risk_assessment(prediction, probability)
        
        # Integrity Section
        if confidence:
            self.add_safety_metrics(confidence, safety_warnings)
            
        self.add_clinical_drivers(shap_plot_path)
        
        # New sections
        if sim_results:
            self.add_simulation_results(sim_results)
            
        self.add_recommendations(recs)
        
        if observations:
            self.add_observations(observations)
            
        return self.output()
